# Generated by the protocol buffer compiler.  DO NOT EDIT!
# type: ignore
# flake8: noqa
# nopycln: file
# pyright: ignore
# mypy: ignore-errors
# fmt: off
# plugin: python-cbproto
# sources: cbi/protobuf/service.proto

from __future__ import annotations

from dataclasses import dataclass

import cbproto


@dataclass(eq=False, repr=False)
class ServiceOptions(cbproto.Message):
    internal: bool = cbproto.bool_field(1)
