# Generated by the protocol buffer compiler.  DO NOT EDIT!
# type: ignore
# flake8: noqa
# nopycln: file
# pyright: ignore
# mypy: ignore-errors
# fmt: off
# plugin: python-cbiproto
# sources: cbi/protobuf/service.proto

from __future__ import annotations

from dataclasses import dataclass

import cbiproto


@dataclass(eq=False, repr=False)
class ServiceOptions(cbiproto.Message):
    internal: bool = cbiproto.bool_field(1)
