# Generated by the protocol buffer compiler.  DO NOT EDIT!
# type: ignore
# flake8: noqa
# nopycln: file
# pyright: ignore
# mypy: ignore-errors
# fmt: off
# plugin: python-betterproto
# sources: internal/protobuf/service.proto

from __future__ import annotations

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class ServiceOptions(betterproto.Message):
    internal: bool = betterproto.bool_field(1)
